import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Architecture_conference",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-full border'>
          <Navbar/>
        </div>
        <div>{children}</div>
        <div className='w-full border'>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
